refactor(etl): introduce `data` directory
cgallegu/semantle-es pull request #18
Opened 2022-02-26 03:36 UTC by cgallegu

Let's use the `data` directory for all ETL files that we use locally to
generate the data base, and that should not be commited or deployed.

2022-02-27 23:03 UTC, jurelmetal requested changes
Please rebase from current main to remove diff related to gunicorn setup.

2022-02-28 02:36 UTC, cgallegu commented
Rebased on top of the current `main`.

2022-02-28 02:37 UTC, jurelmetal commented
THANKS

2022-02-28 02:37 UTC, jurelmetal approved these changes

2022-02-28 02:38 UTC, merged